In [51]:
import pandas as pd
import numpy as np

In [52]:
df = pd.read_json('Headlines_Dataset.json',lines = True)
df.head()

article_link  \
0  https://www.huffingtonpost.com/entry/versace-b...   
1  https://www.huffingtonpost.com/entry/roseanne-...   
2  https://local.theonion.com/mom-starting-to-fea...   
3  https://politics.theonion.com/boehner-just-wan...   
4  https://www.huffingtonpost.com/entry/jk-rowlin...   

                                            headline  is_sarcastic  
0  former versace store clerk sues over secret 'b...             0  
1  the 'roseanne' revival catches up to our thorn...             0  
2  mom starting to fear son's web series closest ...             1  
3  boehner just wants wife to listen, not come up...             1  
4  j.k. rowling wishes snape happy birthday in th...             0

**Let us Extraxt only headlines from given data and Check top 5 observation of Headlines** 

In [53]:
articles = df.iloc[:,1]
print("Top 5 News are:-\n\n")
print(articles.head())

Top 5 News are:-


0    former versace store clerk sues over secret 'b...
1    the 'roseanne' revival catches up to our thorn...
2    mom starting to fear son's web series closest ...
3    boehner just wants wife to listen, not come up...
4    j.k. rowling wishes snape happy birthday in th...
Name: headline, dtype: object


In [54]:
articles.shape

(26709,)

# CSR_Matrix

**Let us make CSR_MATRIX i.e. actually word frequency for each headlines**

*Let me tell you, I am using MaxAbsScaler because it is good for CSR_MATRIX*

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MaxAbsScaler

In [56]:
tfidf = TfidfVectorizer()
csr_matrix = tfidf.fit_transform(articles)
print("Word Frequency of Articles for each documents==>\n")
print(csr_matrix.toarray())

scale = MaxAbsScaler()
articles_transformed = scale.fit_transform(csr_matrix)

Word Frequency of Articles for each documents==>

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# NMF

**NMF : Non-Negative Matrix Factorization**

*I am using NMF to get transformed features of initial articles in which each observation actually represents topic, More concise in actual components are topis and take advantage to find similarities of topic*

In [57]:
from sklearn.decomposition import NMF
nmf = NMF(n_components = 6)
nmf_features = nmf.fit_transform(articles_transformed)

from sklearn.preprocessing import normalize
features_norm = normalize(nmf_features)

# Recommendation

**I am using Cosine Similarities to find similarities among headlines. More than cosine value , less the angle between headlines and more similar the news will be.**

In [58]:
norm_feat = pd.DataFrame(features_norm,index= articles)
current_article = features_norm[30,:]
similarities = norm_feat.dot(current_article)

In [61]:
print("You may like some similar news to this ==> ", df.iloc[30,1])
print("\n")
sim = similarities.nlargest()
score = []
news_sim = []
for i in similarities.nlargest().index:
    news_sim.append(i)
    
for i in similarities.nlargest():
    score.append(i)
    
similar = list(zip(news_sim,score))[1:]

for i,j in similar:
    print(i,"\t","Score==>",j)
    print("\n")

You may like some similar news to this ==>  allies: islamist motive for killing nemtsov is nonsense


is data hoarding necessary for lawful surveillance? 	 Score==> 0.999999998622998


john travolta is very thankful for 'dick poop' 	 Score==> 0.999999094984458


mayo investigator is developing a screening test for endometrial cancer 	 Score==> 0.9999990143221469


bernie sanders' son levi is running for congress 	 Score==> 0.9999934935634357


